export enum ApiErrors {
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    REQUEST_SCHEMA_ERROR = "REQUEST_SCHEMA_ERROR",
    FORBIDDEN = "FORBIDDEN",
    INVALID_PASSWORD = "INVALID_PASSWORD",
    INVALID_EMAIL = "INVALID_EMAIL",
    NO_VALID_OPTION = "NO_VALID_OPTION",
}
